services:
  - type: web
    name: mis-talleres-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://mistalleres_user:5UnIHuLWp16i51679WKXrxIMnJhnH21w@dpg-datdiaek1f9s73frqthg-a/mistalleres
      - key: SPRING_DATASOURCE_USERNAME
        value: mistalleres_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: 5UnIHuLWp16i51679WKXrxIMnJhnH21w
